// <auto-generated />
namespace PMS.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class createnewDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createnewDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121459088_createnewDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
